# Site settings
title: "Cloudman & Docker: A Guide"
email: simon@belluzzo.id.au
description: > # this means to ignore newlines until "baseurl:"
  A guide for both using and setting up Cloudman and Docker to cooperate.
baseurl: "/cloudman-docker-guide" # the subpath of your site, e.g. /blog/
url: "simon.belluzzo.id.au" # the base hostname & protocol for your site
twitter_username: simonalpha
github_username:  simonalpha

# Build settings
markdown: kramdown
