# Site settings
title: "Galaxy, Docker and a hint of CloudMan: A Guide"
email: simon@belluzzo.id.au
description: > # this means to ignore newlines until "baseurl:"
  A guide for both setting up and using Docker for job-running in Galaxy, especially on CloudMan instances.
baseurl: "/cloudman-docker-guide" # the subpath of your site, e.g. /blog/
url: "http://:simon.belluzzo.id.au" # the base hostname & protocol for your site
twitter_username: simonalpha
github_username:  simonalpha

# Build settings
markdown: kramdown
